import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowRight, ImageOff, LockKeyhole, Minus, Package, Plus, ShoppingCart, Store, Trash2 } from 'lucide-react';
import { useState } from 'react';
import BuyerLayout from '../../../Layouts/BuyerLayout';

const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value || 0));

export default function Index({ cart, errors = {} }) {
    const form = useForm({ quantity: 1 });
    const [activeItemId, setActiveItemId] = useState(null);
    const items = cart?.items || [];
    const totalItems = items.reduce((total, item) => total + Number(item.quantity || 0), 0);
    const update = (item, quantity) => { if (!form.processing && item.status === 'active' && Number(item.stock) > 0) { setActiveItemId(item.id); form.setData('quantity', quantity); form.patch(`/buyer/cart/items/${item.id}`, { preserveScroll: true, onFinish: () => setActiveItemId(null) }); } };
    const remove = (item) => { if (!form.processing) { setActiveItemId(item.id); form.delete(`/buyer/cart/items/${item.id}`, { preserveScroll: true, onFinish: () => setActiveItemId(null) }); } };

    return <BuyerLayout><Head title="Keranjang Belanja" /><main className="min-h-screen overflow-x-hidden bg-[#f7f9fb] px-4 py-8 text-[#191c1e] sm:px-6 lg:px-10"><div className="mx-auto max-w-7xl"><div className="mb-8 flex items-center gap-3"><ShoppingCart className="text-[#9d4300]" size={25} aria-hidden="true" /><div><p className="text-sm font-medium text-[#565e74]">Belanja Anda</p><h1 className="font-heading text-3xl font-bold tracking-tight sm:text-4xl">Keranjang Belanja <span className="text-lg font-normal text-[#565e74]">({totalItems} Produk)</span></h1></div></div>{items.length === 0 ? <EmptyCart /> : <div className="grid gap-6 lg:grid-cols-8"><section className="space-y-4 lg:col-span-5" aria-label="Daftar produk dalam keranjang">{items.map((item) => <CartItem key={item.id} item={item} active={form.processing && activeItemId === item.id} error={activeItemId === item.id ? form.errors.quantity || errors.quantity : null} onUpdate={update} onRemove={remove} />)}</section><Summary total={cart.total} /></div>}</div></main></BuyerLayout>;
}

function CartItem({ item, active, error, onUpdate, onRemove }) {
    const unavailable = item.status !== 'active' || Number(item.stock) <= 0;
    const stock = Number(item.stock || 0);
    return <article className="rounded-xl border border-[#e6e8ea] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.04)]"><div className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:p-5"><div className="flex size-20 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-[#e6e8ea] bg-[#f2f4f6] sm:size-24">{item.image_url ? <img src={item.image_url} alt={item.product_name ? `Gambar ${item.product_name}` : 'Gambar produk'} className="size-full object-cover" /> : <ImageOff className="text-[#565e74]" size={30} aria-label="Gambar tidak tersedia" />}</div><div className="min-w-0 flex-1 self-stretch"><div className="flex items-center gap-2 text-sm text-[#565e74]"><Store size={15} aria-hidden="true" /><span>{item.store?.name || 'Toko tidak tersedia'}</span></div><h2 className="mt-1 line-clamp-2 font-semibold">{item.product_name || 'Produk tidak tersedia'}</h2><p className="mt-1 font-semibold text-[#9d4300]">{money(item.price)} <span className="text-sm font-normal text-[#565e74]">/ unit</span></p>{unavailable && <p className="mt-2 text-sm font-semibold text-[#ba1a1a]">Tidak tersedia</p>}{error && <p className="mt-2 text-sm text-[#ba1a1a]" role="alert">{error}</p>}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-[#e6e8ea] pt-3 sm:border-t-0 sm:pt-0"><div className="flex items-center overflow-hidden rounded-lg border border-[#e6e8ea] bg-white"><button type="button" aria-label="Kurangi kuantitas" disabled={unavailable || active} onClick={() => onUpdate(item, Math.max(1, item.quantity - 1))} className="flex size-9 items-center justify-center text-[#565e74] transition hover:bg-[#f2f4f6] disabled:cursor-not-allowed disabled:opacity-40"><Minus size={16} /></button><span className="w-10 text-center text-sm font-semibold" aria-live="polite">{item.quantity}</span><button type="button" aria-label="Tambah kuantitas" disabled={unavailable || active || item.quantity >= stock} onClick={() => onUpdate(item, Math.min(stock, item.quantity + 1))} className="flex size-9 items-center justify-center text-[#565e74] transition hover:bg-[#f2f4f6] disabled:cursor-not-allowed disabled:opacity-40"><Plus size={16} /></button></div><div className="flex items-center gap-3"><div className="text-right"><span className="block text-xs text-[#565e74]">Subtotal</span><span className="font-bold">{money(item.subtotal)}</span></div><button type="button" aria-label="Hapus item" disabled={active} onClick={() => onRemove(item)} className="rounded-lg p-2 text-[#565e74] transition hover:bg-[#f2f4f6] hover:text-[#ba1a1a] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#9d4300] disabled:cursor-not-allowed disabled:opacity-40"><Trash2 size={19} /></button></div></div></div></div></article>;
}

function Summary({ total }) { return <aside className="lg:col-span-3 lg:sticky lg:top-24 lg:self-start"><div className="rounded-xl border border-[#e6e8ea] bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.04)] sm:p-6"><h2 className="text-xl font-bold">Ringkasan Belanja</h2><div className="my-5 h-px bg-[#e6e8ea]" /><div className="flex items-end justify-between"><div><span className="block text-sm text-[#565e74]">Total Belanja</span><span className="text-xs text-[#565e74]">Harga dari server</span></div><span className="text-2xl font-bold tracking-tight text-[#9d4300]">{money(total)}</span></div><Link href="/buyer/checkout" className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-[#f97316] px-6 py-3.5 font-bold text-white transition hover:bg-[#9d4300] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#9d4300]"><span>Lanjut ke Checkout</span><ArrowRight size={19} /></Link><div className="mt-5 flex items-center justify-center gap-2 border-t border-[#e6e8ea] pt-4 text-sm text-[#565e74]"><LockKeyhole size={17} className="text-emerald-600" aria-hidden="true" />Pembayaran aman</div></div></aside>; }

function EmptyCart() { return <section className="rounded-xl border border-[#e6e8ea] bg-white px-6 py-16 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-[#f2f4f6] text-[#9d4300]"><Package size={32} aria-hidden="true" /></div><h2 className="mt-5 text-2xl font-bold">Keranjang Belanja Kosong</h2><p className="mx-auto mt-2 max-w-md text-[#565e74]">Belum ada produk di keranjang Anda. Temukan produk yang Anda butuhkan dan mulai berbelanja.</p><Link href="/buyer/products" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#f97316] px-5 py-3 font-bold text-white transition hover:bg-[#9d4300] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#9d4300]">Mulai Belanja <ArrowRight size={18} /></Link></section>; }