import { Head, router, usePage } from '@inertiajs/react';
import { BadgeCheck, LoaderCircle, MapPin, Pencil, Plus, Star, X } from 'lucide-react';
import { useState } from 'react';
import { useForm as useReactHookForm } from 'react-hook-form';
import { z } from 'zod';
import BuyerLayout from '../../../Layouts/BuyerLayout';

const empty = { label: '', recipient_name: '', phone: '', address: '', city: '', province: '', postal_code: '', is_default: false };
const schema = z.object({ label: z.string().max(100, 'Label maksimal 100 karakter.'), recipient_name: z.string().trim().min(1, 'Nama penerima wajib diisi.').max(255), phone: z.string().trim().min(1, 'Nomor telepon wajib diisi.').max(30), address: z.string().trim().min(1, 'Alamat wajib diisi.'), city: z.string().max(100), province: z.string().max(100), postal_code: z.string().max(20), is_default: z.boolean() });

export default function Index({ addresses = [], regions = {} }) {
    const { props } = usePage();
    const [editing, setEditing] = useState(null);
    const [formOpen, setFormOpen] = useState(false);
    const [generalError, setGeneralError] = useState(null);
    const [processing, setProcessing] = useState(false);
    const { register, handleSubmit, reset, setValue, watch, setError, clearErrors, formState: { errors } } = useReactHookForm({ defaultValues: empty });
    const province = watch('province');
    const openForm = (address = null) => { setEditing(address); setFormOpen(true); const values = address ? fields(address) : empty; reset(values); clearErrors(); setGeneralError(null); };
    const closeForm = () => { setEditing(null); setFormOpen(false); reset(empty); clearErrors(); setGeneralError(null); };
    const submit = (data) => { const result = schema.safeParse(data); if (!result.success) { clearErrors(); result.error.issues.forEach((issue) => setError(issue.path[0], { type: 'client', message: issue.message })); return; } setProcessing(true); const options = { preserveScroll: true, onSuccess: closeForm, onError: (server) => { setGeneralError(server.error ?? 'Alamat gagal disimpan.'); Object.entries(server).forEach(([key, message]) => setError(key, { type: 'server', message })); }, onFinish: () => setProcessing(false) }; editing ? router.put(`/buyer/addresses/${editing.id}`, data, options) : router.post('/buyer/addresses', data, options); };
    const setDefault = (address) => { setProcessing(true); router.patch(`/buyer/addresses/${address.id}/default`, {}, { preserveScroll: true, onFinish: () => setProcessing(false) }); };
    const mergedErrors = Object.fromEntries(Object.entries(errors).map(([key, value]) => [key, value.message]));
    return <BuyerLayout><Head title="Alamat Saya" /><main className="min-h-screen overflow-x-hidden bg-background px-5 py-8 text-foreground sm:px-8 lg:px-10"><div className="mx-auto max-w-5xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Pengaturan</p><h1 className="mt-1 font-heading text-3xl font-bold">Alamat Saya</h1><p className="mt-2 text-secondary">Kelola alamat pengiriman Anda.</p></div><button type="button" onClick={() => openForm()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary-container px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary"><Plus size={18} />Tambah Alamat</button></div>{props.flash?.success && <p className="mt-5 rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800" role="status">{props.flash.success}</p>}{generalError && <p className="mt-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-error" role="alert">{generalError}</p>}{addresses.length === 0 ? <EmptyState onAdd={() => openForm()} /> : <div className="mt-8 grid gap-5 md:grid-cols-2">{addresses.map((address) => <AddressCard key={address.id} address={address} onEdit={() => openForm(address)} onDefault={() => setDefault(address)} processing={processing} />)}</div>}{formOpen && <AddressForm editing={editing} register={register} errors={mergedErrors} onSubmit={handleSubmit(submit)} onClose={closeForm} processing={processing} regions={regions} province={province} setValue={setValue} />}</div></main></BuyerLayout>;
}

function AddressCard({ address, onEdit, onDefault, processing }) { return <article className={`rounded-xl border bg-surface p-5 shadow-sm ${address.is_default ? 'border-primary-container ring-1 ring-primary-container/20' : 'border-surface-container-high'}`}><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-2"><MapPin className="shrink-0 text-primary" size={20} /><h2 className="truncate font-heading font-bold">{address.label || 'Alamat'}</h2></div>{address.is_default && <span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-primary-container/10 px-2.5 py-1 text-xs font-bold text-primary"><BadgeCheck size={14} />UTAMA</span>}</div><div className="mt-4 space-y-1 text-sm"><p className="font-semibold">{address.recipient_name}</p><p className="text-secondary">{address.phone}</p><p className="text-secondary">{[address.address, address.city, address.province, address.postal_code].filter(Boolean).join(', ')}</p></div><div className="mt-5 flex flex-wrap gap-2 border-t border-surface-container-high pt-4"><button type="button" onClick={onEdit} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-surface-container-high px-3 text-sm font-semibold hover:bg-surface-container-low"><Pencil size={16} />Edit</button>{!address.is_default && <button type="button" onClick={onDefault} disabled={processing} className="inline-flex min-h-10 items-center gap-2 rounded-lg px-3 text-sm font-semibold text-primary hover:bg-primary-container/10 disabled:opacity-50"><Star size={16} />Jadikan Utama</button>}</div></article>; }
function EmptyState({ onAdd }) { return <section className="mt-8 rounded-xl border border-dashed border-surface-container-high bg-surface px-6 py-16 text-center"><MapPin className="mx-auto text-primary" size={38} /><h2 className="mt-4 text-xl font-bold">Belum ada alamat</h2><p className="mt-2 text-secondary">Tambahkan alamat pengiriman untuk checkout.</p><button type="button" onClick={onAdd} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-lg bg-primary-container px-4 py-2.5 text-sm font-semibold text-white"><Plus size={18} />Tambah Alamat</button></section>; }
function AddressForm({ editing, register, errors, onSubmit, onClose, processing, regions, province, setValue }) { const fields = [['label', 'Label'], ['recipient_name', 'Nama penerima'], ['phone', 'Nomor telepon'], ['address', 'Alamat'], ['postal_code', 'Kode pos']]; return <section className="mt-8 rounded-xl border border-primary-container/40 bg-surface p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-3"><div><h2 className="font-heading text-xl font-bold">{editing ? 'Edit Alamat' : 'Tambah Alamat'}</h2><p className="mt-1 text-sm text-secondary">Lengkapi informasi alamat pengiriman.</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-secondary hover:bg-surface-container-low" aria-label="Tutup form"><X size={20} /></button></div><form onSubmit={onSubmit} className="mt-6 grid gap-5 sm:grid-cols-2">{fields.map(([name, label]) => <Field key={name} name={name} label={label} register={register} error={errors[name]} textarea={name === 'address'} />)}<SelectField name="province" label="Provinsi" register={register} error={errors.province} options={Object.keys(regions)} onChange={() => setValue('city', '')} /><SelectField name="city" label="Kabupaten/Kota" register={register} error={errors.city} options={regions[province] ?? []} disabled={!province} /><label className="flex min-h-11 items-center gap-3 text-sm font-semibold sm:col-span-2"><input type="checkbox" {...register('is_default')} className="size-4 accent-primary-container" />Jadikan sebagai alamat utama</label><div className="flex flex-col-reverse gap-3 sm:col-span-2 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} disabled={processing} className="min-h-11 rounded-lg border border-surface-container-high px-5 text-sm font-semibold">Batal</button><button type="submit" disabled={processing} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary-container px-5 text-sm font-semibold text-white disabled:opacity-60">{processing && <LoaderCircle size={17} className="animate-spin" />}{processing ? 'Menyimpan...' : 'Simpan Alamat'}</button></div></form></section>; }

function SelectField({ name, label, register, error, options, disabled = false, onChange }) { return <div><label htmlFor={name} className="mb-2 block text-sm font-semibold">{label}</label><select id={name} {...register(name, { onChange })} disabled={disabled} aria-invalid={Boolean(error)} className="w-full rounded-lg border border-surface-container-high bg-surface px-3 py-2.5 outline-none focus:border-primary-container focus:ring-1 focus:ring-primary-container"><option value="">Pilih {label.toLowerCase()}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select>{error && <p className="mt-1.5 text-sm text-error" role="alert">{error.message ?? error}</p>}</div>; }
function Field({ name, label, register, error, textarea }) { const Element = textarea ? 'textarea' : 'input'; return <div className={textarea ? 'sm:col-span-2' : ''}><label htmlFor={name} className="mb-2 block text-sm font-semibold">{label}{['recipient_name', 'phone', 'address'].includes(name) && <span className="ml-1 text-primary">*</span>}</label><Element id={name} rows={textarea ? 4 : undefined} {...register(name)} aria-invalid={Boolean(error)} aria-describedby={error ? `${name}-error` : undefined} className="w-full rounded-lg border border-surface-container-high bg-surface px-3 py-2.5 outline-none focus:border-primary-container focus:ring-1 focus:ring-primary-container" />{error && <p id={`${name}-error`} className="mt-1.5 text-sm text-error" role="alert">{error.message ?? error}</p>}</div>; }
function fields(address) { return { ...empty, ...address, is_default: Boolean(address.is_default) }; }