import { Head, Link, router } from '@inertiajs/react';
import { ChevronLeft, ChevronRight, ClipboardList, Eye, Search } from 'lucide-react';
import { useState } from 'react';
import { OrderStatusBadge, PaymentStatusBadge } from '@/Components/Order/StatusBadge';
import AdminLayout from '../../../Layouts/AdminLayout';

const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value || 0));

export default function Index({ orders, filters = {} }) {
    const [search, setSearch] = useState(filters.search || '');
    const visit = (data) => router.get('/admin/orders', data, { preserveState: true, replace: true });
    const filter = (key, value) => visit({ ...filters, search: search || undefined, [key]: value || undefined });
    const filtered = Boolean(filters.search || filters.payment_status || filters.order_status || filters.payment_method);
    return <AdminLayout><Head title="Pengawasan Pesanan" /><main className="min-h-screen bg-background px-5 py-8 text-foreground sm:px-8 lg:px-10"><div className="mx-auto max-w-[1400px]">
        <header className="border-b border-surface-container-high pb-7"><p className="text-sm font-semibold text-primary">Admin Portal / Pesanan</p><h1 className="mt-2 font-heading text-3xl font-bold sm:text-4xl">Pengawasan Pesanan</h1><p className="mt-2 text-secondary">Pantau pesanan platform, status pembayaran, dan pemenuhan vendor.</p></header>
        <form onSubmit={(event) => { event.preventDefault(); visit({ ...filters, search: search || undefined }); }} className="mt-8 space-y-4 rounded-xl border border-surface-container-high bg-surface p-4 shadow-sm"><label className="relative block"><span className="sr-only">Cari pesanan</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-secondary" size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nomor pesanan, pembeli, atau toko..." className="w-full rounded-lg border border-surface-container-high bg-surface-container-low py-2.5 pl-10 pr-4" /></label><div className="grid grid-cols-1 gap-4 md:grid-cols-3"><Select label="Pembayaran" value={filters.payment_status} onChange={(value) => filter('payment_status', value)} options={[['pending', 'Menunggu'], ['paid', 'Dibayar'], ['failed', 'Gagal']]} /><Select label="Pesanan" value={filters.order_status} onChange={(value) => filter('order_status', value)} options={[['pending', 'Menunggu'], ['processing', 'Diproses'], ['shipped', 'Dikirim'], ['completed', 'Selesai'], ['cancelled', 'Dibatalkan'], ['partially_cancelled', 'Sebagian dibatalkan']]} /><Select label="Metode" value={filters.payment_method} onChange={(value) => filter('payment_method', value)} options={[['bank_transfer', 'Transfer bank'], ['cod', 'Bayar di tempat']]} /></div></form>
        <section className="mt-6 overflow-hidden rounded-xl border border-surface-container-high bg-surface shadow-sm">{orders.data.length === 0 ? <Empty filtered={filtered} /> : <><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-surface-container-low text-xs uppercase text-secondary"><tr><th className="px-6 py-4">Pesanan</th><th className="px-6 py-4">Pembeli</th><th className="px-6 py-4">Vendor</th><th className="px-6 py-4">Total</th><th className="px-6 py-4">Pembayaran</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Aksi</th></tr></thead><tbody className="divide-y divide-surface-container-high">{orders.data.map((order) => <tr key={order.id}><td className="px-6 py-5"><b>{order.order_number}</b><p className="mt-1 text-xs text-secondary">{new Date(order.created_at).toLocaleString('id-ID')}</p></td><td className="px-6 py-5"><b>{order.buyer?.name || '-'}</b><p className="mt-1 text-xs text-secondary">{order.buyer?.email || '-'}</p></td><td className="px-6 py-5"><Vendors groups={order.vendor_groups} /></td><td className="px-6 py-5 font-semibold">{money(order.total_amount)}</td><td className="px-6 py-5"><PaymentStatusBadge status={order.payment_status} /></td><td className="px-6 py-5"><OrderStatusBadge status={order.order_status} /></td><td className="px-6 py-5"><Link href={`/admin/orders/${order.id}`} className="inline-flex items-center gap-2 rounded-lg border border-primary px-3 py-2 font-semibold text-primary"><Eye size={16} />Detail</Link></td></tr>)}</tbody></table></div><Pagination orders={orders} /></>}</section>
    </div></main></AdminLayout>;
}
function Select({ label, value, onChange, options }) { return <label className="text-sm font-semibold">{label}<select value={value || ''} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border border-surface-container-high bg-background px-3 py-2.5 font-normal"><option value="">Semua</option>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function Vendors({ groups = [] }) { return <div>{groups.map((group) => <div key={group.id}>{group.vendor?.name || 'Toko tidak tersedia'} <OrderStatusBadge status={group.status} /></div>)}</div>; }
function Empty({ filtered }) { return <div className="flex flex-col items-center px-6 py-16 text-center"><ClipboardList size={42} className="text-secondary" /><h2 className="mt-4 font-heading text-lg font-bold">{filtered ? 'Tidak ada pesanan sesuai filter' : 'Belum ada pesanan'}</h2></div>; }
function Pagination({ orders }) { return <nav className="flex items-center justify-between border-t border-surface-container-high px-6 py-4 text-sm text-secondary"><span>{orders.from}–{orders.to} dari {orders.total}</span><div className="flex gap-1">{orders.links.map((link, index) => <Link key={`${link.label}-${index}`} href={link.url || '#'} preserveScroll className={`inline-flex size-9 items-center justify-center rounded border ${link.active ? 'border-primary bg-primary text-white' : 'border-surface-container-high'} ${!link.url ? 'pointer-events-none opacity-40' : ''}`}>{index === 0 ? <ChevronLeft size={17} /> : index === orders.links.length - 1 ? <ChevronRight size={17} /> : link.label}</Link>)}</div></nav>; }
