import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { ArrowLeft, Check, Printer, X } from 'lucide-react';
import { useState } from 'react';
import { OrderStatusBadge, PaymentStatusBadge } from '@/Components/Order/StatusBadge';
import AdminLayout from '../../../Layouts/AdminLayout';

const money = (v) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(v || 0));
const methods = { bank_transfer: 'Transfer Bank', cod: 'Bayar di Tempat' };

export default function Show({ order }) {
    const form = useForm({ status: '', reason: '' });
    const [target, setTarget] = useState(null);
    const { flash = {} } = usePage().props;
    const close = () => { setTarget(null); form.resetAndClearErrors(); };
    const submit = (event) => { event.preventDefault(); form.transform((data) => ({ status: target, reason: data.reason || undefined })); form.patch(`/admin/orders/${order.id}/payment-status`, { preserveScroll: true, onSuccess: close }); };
    return <AdminLayout><Head title={`Pesanan ${order.order_number}`} /><main className="min-h-screen bg-background px-5 py-8 text-foreground sm:px-8 lg:px-10"><div className="mx-auto max-w-6xl">
        <Link href="/admin/orders" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft size={17} />Kembali ke Pesanan</Link>
        <header className="mt-5 flex flex-col gap-4 border-b border-surface-container-high pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">Detail Pesanan</p><h1 className="mt-2 font-heading text-3xl font-bold">{order.order_number}</h1><p className="mt-2 text-secondary">{new Date(order.created_at).toLocaleString('id-ID')}</p></div><div className="flex gap-2"><OrderStatusBadge status={order.order_status} /><PaymentStatusBadge status={order.payment_status} /></div></header>
        {flash.success && <p className="mt-5 rounded-lg border border-green-200 bg-green-50 p-3 text-green-800" role="status">{flash.success}</p>}
        <div className="mt-6 grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><Card title="Pembeli"><p className="font-semibold">{order.buyer?.name || '-'}</p><p className="text-sm text-secondary">{order.buyer?.email || '-'}</p></Card><Card title="Alamat Pengiriman"><p className="whitespace-pre-line text-sm text-secondary">{order.shipping_address || '-'}</p></Card><Card title="Grup Vendor">{order.vendor_groups.map((group) => <div key={group.id} className="border-b border-surface-container-high py-4 first:pt-0 last:border-0"><div className="flex justify-between gap-3"><div><b>{group.vendor?.name || 'Toko tidak tersedia'}</b>{group.cancellation_reason && <p className="text-sm text-red-700">Alasan batal: {group.cancellation_reason}</p>}</div><div><OrderStatusBadge status={group.status} /> <b>{money(group.subtotal)}</b></div></div><Items items={group.items} /></div>)}</Card><Card title="Riwayat Pembayaran"><History items={order.payment_history} /></Card></div>
        <aside className="h-fit lg:sticky lg:top-24"><Card title="Pembayaran"><dl className="space-y-4 text-sm"><Row label="Metode" value={methods[order.payment_method] || order.payment_method} /><Row label="Status" value={<PaymentStatusBadge status={order.payment_status} />} /><Row label="Total" value={money(order.total_amount)} /></dl>{order.payment_status === 'paid' && <div className="mt-6 border-t border-surface-container-high pt-5"><a href={`/admin/orders/${order.id}/receipt`} target="_blank" rel="noopener noreferrer" aria-label={`Cetak struk pesanan ${order.order_number} di tab baru`} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 font-semibold text-white hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"><Printer size={17} aria-hidden="true" />Cetak Struk</a></div>}{order.payment_status === 'pending' && <div className="mt-6 border-t border-surface-container-high pt-5"><h2 className="font-heading font-bold">Konfirmasi Pembayaran</h2><div className="mt-3 grid gap-2"><button onClick={() => setTarget('paid')} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 font-semibold text-white"><Check size={17} />Tandai Sudah Dibayar</button><button onClick={() => setTarget('failed')} className="inline-flex items-center justify-center gap-2 rounded-lg border border-red-300 px-4 py-2.5 font-semibold text-red-700"><X size={17} />Tandai Gagal</button></div></div>}</Card></aside></div>
        {target && <Dialog target={target} form={form} close={close} submit={submit} />}
    </div></main></AdminLayout>;
}
function Card({ title, children }) { return <section className="rounded-xl border border-surface-container-high bg-surface p-5 shadow-sm"><h2 className="font-heading text-lg font-bold">{title}</h2><div className="mt-4">{children}</div></section>; }
function Row({ label, value }) { return <div className="flex justify-between gap-4"><dt className="text-secondary">{label}</dt><dd className="font-semibold text-right">{value}</dd></div>; }
function Items({ items = [] }) { return <table className="mt-4 w-full text-sm"><thead className="text-left text-xs uppercase text-secondary"><tr><th>Produk</th><th>Harga</th><th>Qty</th><th className="text-right">Subtotal</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-surface-container-high"><td className="py-3 font-medium">{item.product_name}</td><td>{money(item.price)}</td><td>{item.quantity}</td><td className="text-right font-semibold">{money(item.subtotal)}</td></tr>)}</tbody></table>; }
function History({ items = [] }) { return items.length === 0 ? <p className="text-sm text-secondary">Belum ada riwayat pembayaran.</p> : <ol className="space-y-4">{items.map((item) => <li key={item.id} className="border-l-2 border-primary pl-4"><b>{item.from_status || '-'} menjadi {item.to_status}</b><p className="text-sm text-secondary">{item.actor?.name || 'Sistem'} · {new Date(item.created_at).toLocaleString('id-ID')}</p>{item.reason && <p className="text-sm text-secondary">{item.reason}</p>}</li>)}</ol>; }
function Dialog({ target, form, close, submit }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-xl bg-surface p-6 shadow-xl" role="dialog" aria-modal="true" aria-labelledby="payment-dialog-title"><h2 id="payment-dialog-title" className="font-heading text-xl font-bold">{target === 'paid' ? 'Tandai pembayaran sudah dibayar?' : 'Tandai pembayaran gagal?'}</h2><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Alasan (opsional)<textarea value={form.data.reason} onChange={(e) => form.setData('reason', e.target.value)} className="mt-2 w-full rounded-lg border border-surface-container-high bg-background p-3" rows="3" autoFocus /></label>{form.errors.status && <p className="text-sm text-red-700" role="alert">{form.errors.status}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={close} disabled={form.processing} className="rounded-lg border px-4 py-2 font-semibold">Batal</button><button disabled={form.processing} className="rounded-lg bg-primary px-4 py-2 font-semibold text-white">{form.processing ? 'Memproses...' : 'Konfirmasi'}</button></div></form></div></div>; }
