import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowLeft, ImageOff, LoaderCircle, MapPin, ShoppingBag } from 'lucide-react';
import BuyerLayout from '../../Layouts/BuyerLayout';

const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value || 0));

export default function Checkout({ cart, addresses = [], payment_methods = [], errors = {} }) {
    const form = useForm({ address_id: addresses.find((address) => address.is_default)?.id ?? addresses[0]?.id ?? '', payment_method: payment_methods[0] ?? 'bank_transfer' });
    const submit = (event) => {
        event.preventDefault();
        form.post('/buyer/checkout', { preserveScroll: true });
    };

    return <BuyerLayout><Head title="Checkout" /><main className="min-h-screen overflow-x-hidden bg-[#f7f9fb] px-4 py-8 text-[#191c1e] sm:px-6 lg:px-10"><div className="mx-auto max-w-7xl"><Link href="/buyer/cart" className="inline-flex items-center gap-2 text-sm font-semibold text-[#565e74] hover:text-[#9d4300]"><ArrowLeft size={17} />Kembali ke keranjang</Link><div className="mb-8 mt-5 flex items-center gap-3"><ShoppingBag className="text-[#9d4300]" size={25} aria-hidden="true" /><div><p className="text-sm font-medium text-[#565e74]">Selesaikan pembelian</p><h1 className="font-heading text-3xl font-bold tracking-tight sm:text-4xl">Checkout</h1></div></div>{addresses.length === 0 ? <EmptyAddress /> : <form onSubmit={submit} className="grid gap-6 lg:grid-cols-8"><section className="space-y-6 lg:col-span-5"><AddressSection addresses={addresses} form={form} /><PaymentSection form={form} methods={payment_methods} errors={errors} /></section><Summary cart={cart} form={form} /></form>}</div></main></BuyerLayout>;
}

function AddressSection({ addresses, form }) { return <section className="rounded-xl border border-[#e6e8ea] bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.04)] sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Alamat pengiriman</h2><p className="mt-1 text-sm text-[#565e74]">Pilih alamat milik Anda.</p></div><MapPin className="text-[#9d4300]" size={22} aria-hidden="true" /></div><div className="mt-5 space-y-3">{addresses.map((address) => <label key={address.id} className={`block cursor-pointer rounded-lg border p-4 ${String(form.data.address_id) === String(address.id) ? 'border-[#f97316] bg-[#fff7ed]' : 'border-[#e6e8ea]'}`}><span className="flex gap-3"><input type="radio" name="address_id" value={address.id} checked={String(form.data.address_id) === String(address.id)} onChange={(event) => form.setData('address_id', event.target.value)} className="mt-1 accent-[#f97316]" /><span className="min-w-0"><span className="block font-semibold">{address.label || 'Alamat'}{address.is_default && <span className="ml-2 text-xs font-semibold text-[#9d4300]">Utama</span>}</span><span className="mt-1 block text-sm text-[#565e74]">{address.recipient_name} · {address.phone}</span><span className="mt-1 block text-sm text-[#565e74]">{[address.address, address.city, address.province, address.postal_code].filter(Boolean).join(', ')}</span></span></span></label>)}</div>{form.errors.address_id && <p className="mt-3 text-sm text-[#ba1a1a]" role="alert">{form.errors.address_id}</p>}<Link href="/buyer/addresses" className="mt-4 inline-block text-sm font-semibold text-[#9d4300]">Kelola alamat</Link></section>; }

function PaymentSection({ form, methods, errors }) { return <section className="rounded-xl border border-[#e6e8ea] bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.04)] sm:p-6"><h2 className="text-xl font-bold">Metode pembayaran</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{methods.map((method) => <label key={method} className={`cursor-pointer rounded-lg border p-4 ${form.data.payment_method === method ? 'border-[#f97316] bg-[#fff7ed]' : 'border-[#e6e8ea]'}`}><span className="flex items-center gap-3"><input type="radio" name="payment_method" value={method} checked={form.data.payment_method === method} onChange={(event) => form.setData('payment_method', event.target.value)} className="accent-[#f97316]" /><span className="font-semibold">{method === 'bank_transfer' ? 'Transfer bank' : 'Bayar di tempat (COD)'}</span></span></label>)}</div>{form.errors.payment_method && <p className="mt-3 text-sm text-[#ba1a1a]" role="alert">{form.errors.payment_method}</p>}{errors.cart && <p className="mt-3 text-sm text-[#ba1a1a]" role="alert">{errors.cart}</p>}</section>; }

function Summary({ cart, form }) { return <aside className="lg:col-span-3 lg:sticky lg:top-24 lg:self-start"><div className="rounded-xl border border-[#e6e8ea] bg-white p-5 shadow-[0_1px_2px_rgba(15,23,42,0.04)] sm:p-6"><h2 className="text-xl font-bold">Ringkasan pesanan</h2><div className="mt-5 space-y-4">{(cart?.items || []).map((item) => <div key={item.id} className="flex gap-3"><div className="flex size-14 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-[#f2f4f6]">{item.image_url ? <img src={item.image_url} alt={item.product_name || 'Produk'} className="size-full object-cover" /> : <ImageOff size={22} className="text-[#565e74]" aria-label="Gambar tidak tersedia" />}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.product_name || 'Produk'}</p><p className="text-xs text-[#565e74]">{item.quantity} × {money(item.price)}</p><p className="mt-1 text-sm font-semibold text-[#9d4300]">{money(item.subtotal)}</p></div></div>)}</div><div className="my-5 h-px bg-[#e6e8ea]" /><div className="flex items-center justify-between"><span className="font-semibold">Total</span><span className="text-2xl font-bold text-[#9d4300]">{money(cart?.total)}</span></div><button type="submit" disabled={form.processing || !cart?.items?.length} className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-[#f97316] px-6 py-3.5 font-bold text-white transition hover:bg-[#9d4300] disabled:cursor-not-allowed disabled:opacity-60">{form.processing && <LoaderCircle size={18} className="animate-spin" />}{form.processing ? 'Membuat pesanan...' : 'Buat pesanan'}</button></div></aside>; }

function EmptyAddress() { return <section className="rounded-xl border border-[#e6e8ea] bg-white px-6 py-16 text-center"><MapPin className="mx-auto text-[#9d4300]" size={36} /><h2 className="mt-5 text-2xl font-bold">Belum ada alamat</h2><p className="mx-auto mt-2 max-w-md text-[#565e74]">Tambahkan alamat pengiriman sebelum checkout.</p><Link href="/buyer/addresses" className="mt-6 inline-flex rounded-lg bg-[#f97316] px-5 py-3 font-bold text-white">Kelola alamat</Link></section>; }