import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowLeft, LoaderCircle } from 'lucide-react';
import AdminLayout from '../../../Layouts/AdminLayout';

export default function Edit({ category }) {
    const form = useForm({ name: category.name, description: category.description || '', status: category.status });
    const submit = (event) => { event.preventDefault(); form.put(`/admin/categories/${category.id}`); };
    return <AdminLayout><Head title="Edit Category" /><main className="min-h-screen bg-background px-5 py-10 text-foreground sm:px-8"><section className="mx-auto max-w-2xl rounded-xl border border-surface-container-high bg-surface p-6 shadow-sm sm:p-10"><Link href="/admin/categories" className="inline-flex items-center gap-2 text-sm text-secondary hover:text-primary"><ArrowLeft size={16} /> Back to categories</Link><h1 className="mt-6 font-heading text-3xl font-bold">Edit Category</h1><form onSubmit={submit} className="mt-8 space-y-5"><Field label="Name" name="name" form={form} required /><Field label="Description" name="description" form={form} textarea /><div><label htmlFor="status" className="mb-1.5 block font-medium">Status</label><select id="status" value={form.data.status} onChange={(event) => form.setData('status', event.target.value)} className="w-full rounded-lg border border-surface-container-high bg-white px-3 py-3 outline-none focus:border-primary-container focus:ring-1 focus:ring-primary-container"><option value="active">Active</option><option value="inactive">Inactive</option></select><Error message={form.errors.status} /></div><div className="flex justify-end gap-3"><Link href="/admin/categories" className="rounded-lg border border-surface-container-high px-4 py-2.5 font-semibold text-secondary">Cancel</Link><button disabled={form.processing} className="inline-flex items-center gap-2 rounded-lg bg-primary-container px-5 py-2.5 font-semibold text-white hover:bg-primary disabled:opacity-50">{form.processing && <LoaderCircle size={17} className="animate-spin" />}{form.processing ? 'Saving...' : 'Save changes'}</button></div></form></section></main></AdminLayout>;
}
function Field({ label, name, form, textarea = false, required = false }) { const Element = textarea ? 'textarea' : 'input'; return <div><label htmlFor={name} className="mb-1.5 block font-medium">{label}{required && ' *'}</label><Element id={name} value={form.data[name]} onChange={(event) => form.setData(name, event.target.value)} rows={textarea ? 4 : undefined} className="w-full rounded-lg border border-surface-container-high bg-white px-3 py-3 outline-none focus:border-primary-container focus:ring-1 focus:ring-primary-container" /><Error message={form.errors[name]} /></div>; }
function Error({ message }) { return message ? <p className="mt-1 text-sm text-error" role="alert">{message}</p> : null; }