import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { Edit, Plus, ToggleLeft, ToggleRight } from 'lucide-react';
import AdminLayout from '../../../Layouts/AdminLayout';

export default function Index({ categories }) {
    const items = categories?.data ?? [];
    const { flash = {} } = usePage().props;
    const statusForm = useForm({ status: '' });
    const changeStatus = (category) => statusForm.patch(`/admin/categories/${category.id}/status`, { status: category.status === 'active' ? 'inactive' : 'active' }, { preserveScroll: true });

    return <AdminLayout><Head title="Categories" /><main className="min-h-screen bg-background px-5 py-10 text-foreground sm:px-8 lg:px-15"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-primary">Admin Portal / Catalog</p><h1 className="mt-2 font-heading text-3xl font-bold">Category Management</h1><p className="mt-2 text-secondary">Manage catalog categories and availability.</p></div><Link href="/admin/categories/create" className="inline-flex items-center gap-2 rounded-lg bg-primary-container px-4 py-2.5 font-semibold text-white hover:bg-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><Plus size={18} /> Add Category</Link></div>{flash.success && <p className="mt-5 rounded-lg border border-green-200 bg-green-50 p-3 text-green-700" role="status">{flash.success}</p>}<section className="mt-8 overflow-hidden rounded-xl border border-surface-container-high bg-surface shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-surface-container-low text-sm text-secondary"><tr><th className="px-5 py-4">Name</th><th className="px-5 py-4">Slug</th><th className="px-5 py-4">Description</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Created</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{items.map((category) => <tr className="border-t border-surface-container-high" key={category.id}><td className="px-5 py-4 font-semibold">{category.name}</td><td className="px-5 py-4 font-mono text-sm text-secondary">{category.slug}</td><td className="max-w-xs px-5 py-4 text-secondary">{category.description || '—'}</td><td className="px-5 py-4"><StatusBadge status={category.status} /></td><td className="px-5 py-4 text-sm text-secondary">{new Date(category.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link href={`/admin/categories/${category.id}/edit`} className="rounded-lg p-2 text-secondary hover:bg-surface-container-low hover:text-primary" aria-label={`Edit ${category.name}`}><Edit size={17} /></Link><button type="button" onClick={() => changeStatus(category)} disabled={statusForm.processing} className="rounded-lg p-2 text-secondary hover:bg-surface-container-low hover:text-primary" aria-label={`Toggle ${category.name} status`}>{category.status === 'active' ? <ToggleRight size={18} /> : <ToggleLeft size={18} />}</button></div></td></tr>)}</tbody></table></div>{items.length === 0 && <p className="p-8 text-center text-sm text-secondary">No categories found.</p>}<Pagination links={categories?.links} /></section></div></main></AdminLayout>;
}

function StatusBadge({ status }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${status === 'active' ? 'bg-green-50 text-green-700' : 'bg-surface-container text-secondary'}`}>{status}</span>; }
function Pagination({ links = [] }) { return links.length > 3 && <nav className="flex flex-wrap gap-2 border-t border-surface-container-high p-4" aria-label="Pagination">{links.map((link, index) => <Link key={index} href={link.url || '#'} preserveScroll className={`rounded-lg border px-3 py-1.5 text-sm ${link.active ? 'border-primary bg-primary text-white' : 'border-surface-container-high text-secondary'} ${!link.url ? 'pointer-events-none opacity-40' : ''}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</nav>; }