import { Head, Link } from '@inertiajs/react';
import { ClipboardList, Package, ShoppingCart, Store, Users } from 'lucide-react';
import AdminLayout from '../../Layouts/AdminLayout';

export default function Dashboard({ stats = {}, recentOrders = [], recentProducts = [] }) {
    return <AdminLayout><Head title="Admin Dashboard" /><main className="mx-auto w-full max-w-[1440px] space-y-8 p-5 sm:p-8 lg:p-10"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="font-heading text-2xl font-bold tracking-tight sm:text-3xl">Dashboard Utama Administrator</h1><p className="mt-2 text-sm leading-6 text-secondary sm:text-base">Pantau metrik pengguna, transaksi, dan aktivitas vendor secara real-time</p></div><span className="inline-flex w-fit items-center gap-2 rounded-lg border border-surface-container-high bg-surface px-3 py-2 text-sm font-semibold text-secondary"><ClipboardList size={16} /> Data platform</span></header><section className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-4" aria-label="Platform statistics">{[['users', 'Total Users', 'pengguna terdaftar', Users], ['vendors', 'Total Vendors', 'vendor terdaftar', Store], ['products', 'Total Products', 'produk terdaftar', Package], ['orders', 'Total Orders', 'pesanan platform', ShoppingCart]].map(([key, label, description, Icon]) => <article key={key} className="rounded-xl border border-surface-container-high bg-surface p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><span className="text-sm font-semibold text-secondary">{label}</span><span className="flex size-9 items-center justify-center rounded-lg bg-surface-container-low text-primary"><Icon size={19} /></span></div><p className="font-heading text-3xl font-bold">{Number(stats[key] ?? 0).toLocaleString('id-ID')}</p><p className="mt-1 text-sm text-secondary">{description}</p></article>)}</section><section className="grid grid-cols-1 gap-6 xl:grid-cols-2"><OrdersPanel orders={recentOrders} /><ProductsPanel products={recentProducts} /></section></main></AdminLayout>;
}

function OrdersPanel({ orders }) { return <article className="overflow-hidden rounded-xl border border-surface-container-high bg-surface shadow-sm"><PanelHeader title="Pesanan Terbaru Platform" description="Aktivitas pembelian terbaru di platform" />{orders.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-surface-container-low text-xs uppercase tracking-wide text-secondary"><tr>{['Order ID', 'Pembeli', 'Vendor', 'Nilai', 'Status'].map((heading) => <th className="px-5 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-t border-surface-container-high"><td className="whitespace-nowrap px-5 py-4 font-semibold">{order.order_number}</td><td className="px-5 py-4">{order.buyer_name}</td><td className="px-5 py-4 text-secondary">{order.vendor_name}</td><td className="whitespace-nowrap px-5 py-4">{formatCurrency(order.total_amount)}</td><td className="px-5 py-4"><StatusBadge status={order.order_status} /></td></tr>)}</tbody></table></div> : <EmptyState label="Belum ada pesanan terbaru." />}</article>; }
function ProductsPanel({ products }) { return <article className="overflow-hidden rounded-xl border border-surface-container-high bg-surface shadow-sm"><PanelHeader title="Produk Terbaru" description="Produk terbaru dari vendor platform" />{products.length ? <div className="divide-y divide-surface-container-high">{products.map((product) => <div key={product.id} className="flex items-center gap-3 p-4 sm:gap-4"><div className="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-surface-container-high bg-surface-container-low text-primary">{product.image_url ? <img src={product.image_url} alt={product.name} className="size-full object-cover" /> : <Package size={20} />}</div><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{product.name}</h3><p className="mt-1 truncate text-xs text-secondary">{product.vendor_name} <span className="px-1">•</span> {product.category_name}</p><p className="mt-1 text-sm font-bold">{formatCurrency(product.price)}</p></div><div className="flex shrink-0 flex-col items-end gap-2"><StatusBadge status={product.status} /><Link href="/admin/products" className="text-xs font-semibold text-primary">Lihat produk</Link></div></div>)}</div> : <EmptyState label="Belum ada produk terbaru." />}</article>; }
function PanelHeader({ title, description }) { return <header className="border-b border-surface-container-high p-5"><h2 className="font-heading text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-secondary">{description}</p></header>; }
function EmptyState({ label }) { return <p className="p-8 text-center text-sm text-secondary">{label}</p>; }
function StatusBadge({ status }) { return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${status === 'active' || status === 'completed' ? 'border-green-200 bg-green-50 text-green-700' : 'border-surface-container-high bg-surface-container-low text-secondary'}`}>{status}</span>; }
function formatCurrency(value) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value)); }