import { Link, useForm, usePage } from '@inertiajs/react';
import { Home, LogOut, Menu, Package, ShoppingCart, ShoppingBag, UserRound, X } from 'lucide-react';
import { useState } from 'react';

const navigation = [
    { label: 'Home', href: '/buyer/dashboard', icon: Home, exact: true },
    { label: 'Products', href: '/buyer/products', icon: Package },
    { label: 'Cart', href: '/buyer/cart', icon: ShoppingCart },
    { label: 'Orders', href: '/buyer/orders', icon: ShoppingBag },
    { label: 'Profile', href: '/buyer/profile', icon: UserRound },
];

export default function BuyerLayout({ children }) {
    const [mobileOpen, setMobileOpen] = useState(false);
    const { props } = usePage();
    const logout = useForm();
    const currentPath = window.location.pathname;
    const submitLogout = (event) => { event.preventDefault(); logout.post('/logout'); };
    const isActive = ({ href, exact }) => exact ? currentPath === href : currentPath === href || currentPath.startsWith(`${href}/`);
    const links = (onClick) => navigation.map(({ label, href, icon: Icon, exact }) => <Link key={href} href={href} onClick={onClick} aria-current={isActive({ href, exact }) ? 'page' : undefined} className={`flex min-h-11 items-center gap-2 rounded-lg px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${isActive({ href, exact }) ? 'bg-primary-container/10 text-primary' : 'text-secondary hover:bg-surface-container-low hover:text-foreground'}`}><Icon size={17} />{label}</Link>);
    return <div className="min-h-screen bg-background text-foreground">
        <header className="sticky top-0 z-40 border-b border-surface-container-high bg-surface/95 shadow-sm backdrop-blur"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-4 px-5 sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button type="button" className="rounded-lg p-2 text-secondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary lg:hidden" onClick={() => setMobileOpen(true)} aria-label="Buka navigasi" aria-expanded={mobileOpen} aria-controls="buyer-mobile-navigation"><Menu size={21} /></button><Link href="/buyer/dashboard" className="flex items-center gap-2 font-heading text-lg font-bold"><span className="flex size-8 items-center justify-center rounded-md bg-primary-container text-sm text-white">M</span>MarketPlace</Link></div><nav className="hidden items-center gap-1 lg:flex" aria-label="Navigasi buyer">{links()}</nav><div className="hidden items-center gap-3 sm:flex"><div className="min-w-0 text-right"><p className="max-w-32 truncate text-sm font-semibold">{props.auth?.user?.name ?? 'Buyer'}</p><p className="text-xs text-secondary">{props.auth?.user?.email ?? ''}</p></div><span className="flex size-9 items-center justify-center overflow-hidden rounded-full bg-primary-container/15 font-heading font-bold text-primary">{props.auth?.user?.avatar_url ? <img src={props.auth.user.avatar_url} alt="Avatar buyer" className="size-full object-cover" /> : props.auth?.user?.name?.charAt(0)?.toUpperCase() ?? 'B'}</span></div></div></header>
        {mobileOpen && <div className="fixed inset-0 z-50 lg:hidden"><button type="button" className="absolute inset-0 bg-black/30" onClick={() => setMobileOpen(false)} aria-label="Tutup navigasi" /><aside id="buyer-mobile-navigation" className="relative flex h-full w-72 flex-col bg-surface p-5 shadow-xl"><div className="flex items-center justify-between"><span className="font-heading text-lg font-bold">Navigasi</span><button type="button" className="rounded-lg p-2 text-secondary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" onClick={() => setMobileOpen(false)} aria-label="Tutup navigasi"><X size={20} /></button></div><nav className="mt-8 space-y-1" aria-label="Navigasi buyer mobile">{links(() => setMobileOpen(false))}</nav><div className="mt-auto border-t border-surface-container-high pt-4"><p className="truncate text-sm font-semibold">{props.auth?.user?.name ?? 'Buyer'}</p><p className="truncate text-xs text-secondary">{props.auth?.user?.email ?? ''}</p><form onSubmit={submitLogout} className="mt-4"><button type="submit" className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm font-semibold text-secondary hover:bg-surface-container-low focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><LogOut size={18} />Keluar</button></form></div></aside></div>}
        <div>{children}</div><footer className="border-t border-surface-container-high bg-surface px-5 py-10 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 font-heading text-lg font-bold"><span className="flex size-8 items-center justify-center rounded-md bg-primary-container text-sm text-white">M</span>MarketPlace</div><p className="mt-3 max-w-sm text-sm leading-6 text-secondary">Platform multi-vendor untuk menemukan produk dari berbagai toko.</p></div><form onSubmit={submitLogout}><button type="submit" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-surface-container-high px-4 text-sm font-semibold text-secondary hover:bg-surface-container-low focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><LogOut size={17} />Keluar</button></form></div><div className="mt-8 border-t border-surface-container-high pt-5 text-xs text-secondary">© 2026 MarketPlace. Platform multi-vendor.</div></div></footer>
    </div>;
}