import { Head, Link } from '@inertiajs/react';
import { ArrowRight, ChevronLeft, ChevronRight, ImageOff, Package, Store } from 'lucide-react';
import BuyerLayout from '../../../Layouts/BuyerLayout';
import { OrderStatusBadge, PaymentStatusBadge } from '@/Components/Order/StatusBadge';

const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value || 0));

export default function Index({ orders }) {
    const items = orders?.data || [];
    return <BuyerLayout><Head title="Pesanan Saya" /><main className="min-h-screen bg-[#f7f9fb] px-4 py-8 text-[#191c1e] sm:px-6 lg:px-10"><div className="mx-auto max-w-5xl"><header className="mb-8"><p className="text-sm font-medium text-[#9d4300]">Riwayat belanja</p><h1 className="mt-1 font-heading text-3xl font-bold tracking-tight sm:text-4xl">Pesanan Saya</h1><p className="mt-2 text-[#565e74]">Pantau status dan detail pesanan Anda.</p></header>{items.length ? <div className="space-y-4">{items.map((order) => <OrderCard key={order.id} order={order} />)}<Pagination previous={orders.prev_page_url} next={orders.next_page_url} /></div> : <EmptyOrders />}</div></main></BuyerLayout>;
}

function OrderCard({ order }) {
    const date = order.created_at ? new Date(order.created_at).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' }) : '-';
    const items = (order.vendor_groups || []).flatMap((group) => group.items || []);
    return <article className="rounded-xl border border-[#e6e8ea] bg-white shadow-[0_1px_2px_rgba(15,23,42,0.04)]"><div className="flex flex-col gap-3 border-b border-[#e6e8ea] p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div><p className="font-semibold">#{order.order_number}</p><p className="mt-1 text-sm text-[#565e74]">{date}</p></div><div className="flex flex-wrap gap-2"><OrderStatusBadge status={order.order_status} /><PaymentStatusBadge status={order.payment_status} /></div></div><div className="space-y-3 p-4 sm:p-5">{items.slice(0, 3).map((item) => <ItemPreview key={item.id} item={item} />)}{items.length > 3 && <p className="text-sm text-[#565e74]">+ {items.length - 3} produk lainnya</p>}<div className="flex flex-col gap-4 border-t border-[#e6e8ea] pt-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-[#565e74]">Total Pesanan</p><p className="text-lg font-bold text-[#9d4300]">{money(order.total_amount)}</p></div><Link href={`/buyer/orders/${order.id}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[#f97316] px-4 py-3 text-sm font-bold text-white hover:bg-[#9d4300] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#9d4300]">Lihat Detail <ArrowRight size={17} /></Link></div></div></article>;
}

function ItemPreview({ item }) { return <div className="flex min-w-0 items-center gap-3"><div className="flex size-16 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-[#f2f4f6]">{item.image_url ? <img src={item.image_url} alt={`Gambar ${item.product_name || 'produk'}`} className="size-full object-cover" /> : <ImageOff size={24} className="text-[#565e74]" aria-label="Gambar tidak tersedia" />}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{item.product_name || 'Produk tidak tersedia'}</p><p className="mt-1 flex items-center gap-1 text-sm text-[#565e74]"><Store size={14} aria-hidden="true" />{item.vendor?.name || 'Toko tidak tersedia'} · {item.quantity}x</p></div></div>; }
function Pagination({ previous, next }) { return previous || next ? <nav className="flex items-center justify-center gap-2 pt-4" aria-label="Pagination pesanan"><PaginationLink url={previous} icon={<ChevronLeft size={17} />} label="Sebelumnya" /><span className="text-sm text-[#565e74]">Halaman pesanan</span><PaginationLink url={next} icon={<ChevronRight size={17} />} label="Berikutnya" /></nav> : null; }
function PaginationLink({ url, icon, label }) { return <Link href={url || '#'} aria-disabled={!url} onClick={(event) => !url && event.preventDefault()} aria-label={label} className={`inline-flex min-h-11 items-center justify-center rounded-lg border border-[#e6e8ea] bg-white px-3 text-[#565e74] hover:border-[#f97316] hover:text-[#9d4300] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#9d4300] ${!url ? 'pointer-events-none opacity-40' : ''}`}>{icon}</Link>; }
function EmptyOrders() { return <section className="rounded-xl border border-[#e6e8ea] bg-white px-6 py-16 text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-[#f2f4f6] text-[#9d4300]"><Package size={32} aria-hidden="true" /></div><h2 className="mt-5 text-2xl font-bold">Belum Ada Pesanan</h2><p className="mx-auto mt-2 max-w-md text-[#565e74]">Pesanan Anda akan muncul di sini setelah checkout berhasil.</p><Link href="/buyer/products" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#f97316] px-5 py-3 font-bold text-white hover:bg-[#9d4300] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#9d4300]">Mulai Belanja <ArrowRight size={18} /></Link></section>; }