import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, ImageOff, MapPin, Printer, Store } from 'lucide-react';
import BuyerLayout from '../../../Layouts/BuyerLayout';
import { OrderStatusBadge, PaymentStatusBadge } from '@/Components/Order/StatusBadge';

const money = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value || 0));
const methods = { bank_transfer: 'Transfer Bank', cod: 'Bayar di Tempat' };

export default function Show({ order }) {
    const shipping = order.shipping || {};
    const address = [shipping.address, shipping.city, shipping.province, shipping.postal_code].filter(Boolean).join(', ');
    return <BuyerLayout><Head title={`Pesanan #${order.order_number}`} /><main className="min-h-screen bg-[#f7f9fb] px-4 py-8 text-[#191c1e] sm:px-6 lg:px-10"><div className="mx-auto max-w-5xl"><Link href="/buyer/orders" className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[#565e74] hover:text-[#9d4300]"><ArrowLeft size={18} />Kembali ke Pesanan</Link><header className="mt-6 flex flex-col gap-4 border-b border-[#e6e8ea] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[#565e74]">Detail Pesanan</p><h1 className="mt-1 text-3xl font-bold">#{order.order_number}</h1><p className="mt-2 text-sm text-[#565e74]">{order.created_at ? new Date(order.created_at).toLocaleDateString('id-ID') : '-'}</p></div><div className="flex flex-wrap gap-2"><OrderStatusBadge status={order.order_status} /><PaymentStatusBadge status={order.payment_status} /></div></header><div className="mt-6 grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><section className="rounded-xl border border-[#e6e8ea] bg-white p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><MapPin size={19} className="text-[#9d4300]" />Informasi Pengiriman</h2><div className="mt-4 space-y-1 text-sm text-[#565e74]"><p className="font-semibold text-[#191c1e]">{shipping.recipient_name || 'Penerima tidak tersedia'}</p>{shipping.phone && <p>{shipping.phone}</p>}<p>{address || order.shipping_address || 'Alamat tidak tersedia'}</p></div></section><section className="rounded-xl border border-[#e6e8ea] bg-white p-5"><h2 className="text-lg font-bold">Produk Dipesan</h2><div className="mt-4 space-y-6">{(order.vendor_groups || []).map((group) => <section key={group.id}><div className="mb-3 flex flex-wrap items-center justify-between gap-2 border-b border-[#e6e8ea] pb-3"><div className="flex items-center gap-2 font-semibold"><Store size={16} />{group.vendor?.name || 'Toko tidak tersedia'}</div><div className="flex items-center gap-2 text-sm"><OrderStatusBadge status={group.status} /><span className="font-semibold">{money(group.subtotal)}</span></div></div>{(group.items || []).map((item) => <OrderItem key={item.id} item={item} />)}</section>)}</div></section></div><Summary order={order} /></div></div></main></BuyerLayout>;
}

function OrderItem({ item }) { return <div className="flex gap-3 border-b border-[#e6e8ea] pb-4 last:border-0 last:pb-0"><div className="flex size-20 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-[#f2f4f6]">{item.image_url ? <img src={item.image_url} alt={`Gambar ${item.product_name || 'produk'}`} className="size-full object-cover" /> : <ImageOff size={26} className="text-[#565e74]" />}</div><div className="min-w-0 flex-1"><p className="font-semibold">{item.product_name || 'Produk tidak tersedia'}</p><div className="mt-2 flex flex-wrap gap-x-4 text-sm text-[#565e74]"><span>{money(item.price)} × {item.quantity}</span><span className="font-semibold text-[#191c1e]">{money(item.subtotal)}</span></div></div></div>; }
function Summary({ order }) { return <aside className="h-fit rounded-xl border border-[#e6e8ea] bg-white p-5 lg:sticky lg:top-24"><h2 className="text-lg font-bold">Ringkasan Pesanan</h2><dl className="mt-5 space-y-3 border-b border-[#e6e8ea] pb-5 text-sm"><div className="flex justify-between gap-4"><dt className="text-[#565e74]">Metode Pembayaran</dt><dd className="text-right font-semibold">{methods[order.payment_method] || order.payment_method}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#565e74]">Status Pembayaran</dt><dd className="text-right"><PaymentStatusBadge status={order.payment_status} /></dd></div></dl><div className="flex items-center justify-between pt-5"><span className="font-semibold">Total</span><span className="text-xl font-bold text-[#9d4300]">{money(order.total_amount)}</span></div>{order.payment_status === 'paid' && <div className="mt-5 border-t border-[#e6e8ea] pt-5"><a href={`/buyer/orders/${order.id}/receipt`} target="_blank" rel="noopener noreferrer" aria-label={`Cetak struk pesanan ${order.order_number} di tab baru`} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#f97316] px-4 py-2.5 font-bold text-white hover:bg-[#9d4300] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#9d4300] focus-visible:ring-offset-2"><Printer size={17} aria-hidden="true" />Cetak Struk</a></div>}</aside>; }